language: cpp
dist: trusty
sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7']
    env: COMPILER=g++-7
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['clang-6.0', 'g++-7']
    env: COMPILER=clang++-6.0
  - os: osx
    osx_image: xcode10
    compiler: clang
    env: COMPILER=clang++

notifications:
  email:
    on_success: never
    on_failure: always

install:
- echo ${PATH}
- cmake --version
- export CXX=${COMPILER}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v

script:
- mkdir -p build && cd build
- cmake -DBUILD_TESTING=ON -DBUILD_LIB=ON .. && make -j4
- CTEST_OUTPUT_ON_FAILURE=1 ctest --timeout 5 -C Debug -j4
