name: coverage

on: [push, pull_request]

jobs:

  coveralls:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Reattach HEAD
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    - name: Compile tests
      working-directory: build
      env:
        CXXFLAGS: "-O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
        CXX: g++
      run: |
        cmake -DBUILD_TESTING=ON -DBUILD_LIB=ON ..
        make -j4
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j4
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        version: 3.7
    - name: Update coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install --upgrade wheel
        pip install cpp-coveralls
        coveralls --gcov gcov-7 --gcov-options '\-lp' -r . -b build -x cpp -x hpp -e deps -i src
